<script lang="ts">
  import { TOOL_INFO, type ToolId } from '$lib/types/tools';
  
  let joinCode = $state('');
  
  const tools: { id: ToolId; status: 'live' | 'coming' }[] = [
    { id: 'shuffler', status: 'live' },
    { id: 'timer', status: 'live' },
    { id: 'poll', status: 'live' },
    { id: 'survey', status: 'live' },
    { id: 'checkin', status: 'coming' },
  ];
</script>

<svelte:head>
  <title>Event Tools Lab - AI-Built Tools for Event Organizers</title>
  <meta name="description" content="Event organizer tools built entirely by AI from user requests. An experiment in agentic development - no human coding, just AI and your needs." />
</svelte:head>

<main>
  <!-- Header -->
  <header class="site-header">
    <a href="/" class="header-brand">
      <span>🧪</span>
      <span>Event Tools Lab</span>
    </a>
    <nav class="header-nav">
      <a href="#tools">Tools</a>
      <a href="/create" class="header-cta">Create Event</a>
    </nav>
  </header>

  <!-- Hero Section -->
  <section class="hero">
    <div class="hero-badge">
      <span class="pulse"></span>
      <span>🤖 100% AI-Built</span>
    </div>
    <h1>Focus on Your Event,<br/>Not the Tech</h1>
    <p class="hero-subtitle">
      Simple, powerful tools that let event organizers do what matters most — 
      <strong>connect people</strong>.
    </p>
    
    <div class="hero-actions">
      <a href="/create" class="btn-hero primary">
        <span>✨</span> Create Event
      </a>
      <div class="join-inline">
        <span class="join-text">or</span>
        <form action="/join" method="GET" class="join-form-inline">
          <input 
            type="text" 
            name="code" 
            bind:value={joinCode}
            placeholder="Event code"
            maxlength="10"
            autocomplete="off"
          />
          <button type="submit" disabled={!joinCode.trim()}>Join</button>
        </form>
      </div>
    </div>
  </section>

  <!-- The Experiment Section -->
  <section class="experiment">
    <div class="experiment-header">
      <span class="experiment-icon">🧪</span>
      <h2>The Experiment</h2>
    </div>
    <div class="experiment-content">
      <p class="experiment-lead">
        <strong>Can a fully functional app be built without human developers?</strong>
      </p>
      <p>
        This entire platform is being developed by <strong>agentic AI</strong> — guided only by 
        user needs and feedback. No human writes the code. We're exploring the boundaries of 
        AI-assisted development to understand where AI excels and where human expertise 
        remains essential.
      </p>
      <div class="experiment-stats">
        <div class="stat">
          <span class="stat-value">0</span>
          <span class="stat-label">Lines written by humans</span>
        </div>
        <div class="stat">
          <span class="stat-value">100%</span>
          <span class="stat-label">AI-generated code</span>
        </div>
        <div class="stat">
          <span class="stat-value">∞</span>
          <span class="stat-label">User-driven decisions</span>
        </div>
      </div>
      <p class="experiment-note">
        <em>Every feature, every fix, every line of code — generated by Claude in response to 
        real user requests. This is an exploration of what's possible today.</em>
      </p>
    </div>
  </section>

  <!-- Tools Section -->
  <section class="tools" id="tools">
    <div class="section-header">
      <h2>Your Toolkit</h2>
      <p>Use standalone or connect to an event. No signup required.</p>
    </div>
    
    <div class="tools-grid">
      {#each tools as tool}
        {@const info = TOOL_INFO[tool.id]}
        {#if tool.status === 'live'}
          <a href="/tools/{tool.id}" class="tool-card">
            <div class="tool-icon">{info.emoji}</div>
            <div class="tool-content">
              <h3>{info.name}</h3>
              <p>{info.description}</p>
            </div>
            <span class="tool-arrow">→</span>
          </a>
        {:else}
          <div class="tool-card coming">
            <div class="tool-icon">{info.emoji}</div>
            <div class="tool-content">
              <h3>{info.name}</h3>
              <p>{info.description}</p>
            </div>
            <span class="coming-badge">Soon</span>
          </div>
        {/if}
      {/each}
    </div>
  </section>

  <!-- How It Works -->
  <section class="how-it-works">
    <div class="section-header">
      <h2>Dead Simple</h2>
      <p>Get started in under a minute</p>
    </div>
    <div class="steps">
      <div class="step">
        <div class="step-icon">🎯</div>
        <h3>Create</h3>
        <p>Start an event, get a code instantly</p>
      </div>
      <div class="step-connector"></div>
      <div class="step">
        <div class="step-icon">📤</div>
        <h3>Share</h3>
        <p>Send the code — no accounts needed</p>
      </div>
      <div class="step-connector"></div>
      <div class="step">
        <div class="step-icon">🚀</div>
        <h3>Run</h3>
        <p>Use tools, engage your audience</p>
      </div>
    </div>
  </section>

  <!-- Request Section -->
  <section class="request">
    <div class="request-content">
      <h2>Shape This Experiment</h2>
      <p>
        Need a tool we don't have? Your request becomes the AI's next task. 
        Watch it get built in real-time.
      </p>
      <a href="https://github.com/dmgrok/unconf/issues/new?template=tool-request.yml" class="btn-request">
        <span>📬</span> Request a Tool
      </a>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="footer-content">
      <div class="footer-brand">
        <span class="footer-logo">🧪</span>
        <span>Event Tools Lab</span>
      </div>
      <p class="footer-experiment">
        An experiment in AI-only development
      </p>
      <div class="footer-links">
        <a href="https://github.com/dmgrok/unconf">GitHub</a>
        <span class="footer-sep">•</span>
        <span>Built by Claude</span>
        <span class="footer-sep">•</span>
        <span>Guided by humans</span>
      </div>
    </div>
  </footer>
</main>

<style>
  :global(body) {
    margin: 0;
    background: #0a0a0f;
    color: #e4e4e7;
  }

  main {
    min-height: 100vh;
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
  }

  /* Header */
  .site-header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 100;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem 2rem;
    background: rgba(10, 10, 15, 0.8);
    backdrop-filter: blur(12px);
    border-bottom: 1px solid rgba(255, 255, 255, 0.05);
  }

  .header-brand {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-weight: 600;
    color: #e4e4e7;
    text-decoration: none;
    font-size: 1rem;
  }

  .header-brand:hover {
    color: #fff;
  }

  .header-nav {
    display: flex;
    align-items: center;
    gap: 1.5rem;
  }

  .header-nav a {
    color: #a1a1aa;
    text-decoration: none;
    font-size: 0.9rem;
    transition: color 0.2s;
  }

  .header-nav a:hover {
    color: #fff;
  }

  .header-cta {
    padding: 0.5rem 1rem !important;
    background: rgba(99, 102, 241, 0.2) !important;
    border: 1px solid rgba(99, 102, 241, 0.3);
    border-radius: 8px;
    color: #a5b4fc !important;
  }

  .header-cta:hover {
    background: rgba(99, 102, 241, 0.3) !important;
    color: #fff !important;
  }

  /* Hero Section */
  .hero {
    min-height: 70vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    padding: 6rem 1.5rem 4rem;
    background: linear-gradient(180deg, #0f0f18 0%, #0a0a0f 100%);
    position: relative;
    overflow: hidden;
  }

  .hero::before {
    content: '';
    position: absolute;
    top: 0;
    left: 50%;
    transform: translateX(-50%);
    width: 800px;
    height: 600px;
    background: radial-gradient(ellipse, rgba(99, 102, 241, 0.15) 0%, transparent 70%);
    pointer-events: none;
  }

  .hero-badge {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem 1rem;
    background: rgba(99, 102, 241, 0.1);
    border: 1px solid rgba(99, 102, 241, 0.3);
    border-radius: 100px;
    font-size: 0.85rem;
    color: #a5b4fc;
    margin-bottom: 2rem;
    position: relative;
  }

  .pulse {
    width: 8px;
    height: 8px;
    background: #22c55e;
    border-radius: 50%;
    animation: pulse 2s infinite;
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50% { opacity: 0.5; transform: scale(1.2); }
  }

  .hero h1 {
    font-size: clamp(2.5rem, 6vw, 4rem);
    font-weight: 700;
    line-height: 1.1;
    margin: 0 0 1.5rem;
    background: linear-gradient(135deg, #fff 0%, #a5b4fc 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    max-width: 700px;
  }

  .hero-subtitle {
    font-size: 1.25rem;
    color: #a1a1aa;
    max-width: 500px;
    margin: 0 0 2.5rem;
    line-height: 1.6;
  }

  .hero-subtitle strong {
    color: #e4e4e7;
  }

  .hero-actions {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1.5rem;
  }

  .btn-hero {
    display: inline-flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem 2rem;
    font-size: 1.1rem;
    font-weight: 600;
    border-radius: 12px;
    text-decoration: none;
    transition: all 0.2s ease;
  }

  .btn-hero.primary {
    background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
    color: white;
    box-shadow: 0 4px 20px rgba(99, 102, 241, 0.4);
  }

  .btn-hero.primary:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 30px rgba(99, 102, 241, 0.5);
  }

  .join-inline {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .join-text {
    color: #71717a;
    font-size: 0.9rem;
  }

  .join-form-inline {
    display: flex;
    gap: 0.5rem;
  }

  .join-form-inline input {
    width: 120px;
    padding: 0.75rem 1rem;
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 8px;
    color: white;
    font-size: 0.9rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    text-align: center;
  }

  .join-form-inline input::placeholder {
    text-transform: none;
    letter-spacing: normal;
    color: #71717a;
  }

  .join-form-inline input:focus {
    outline: none;
    border-color: #6366f1;
    background: rgba(99, 102, 241, 0.1);
  }

  .join-form-inline button {
    padding: 0.75rem 1.25rem;
    background: rgba(255, 255, 255, 0.1);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 8px;
    color: white;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
  }

  .join-form-inline button:hover:not(:disabled) {
    background: rgba(255, 255, 255, 0.15);
    border-color: rgba(255, 255, 255, 0.2);
  }

  .join-form-inline button:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  /* Experiment Section */
  .experiment {
    max-width: 800px;
    margin: 0 auto;
    padding: 5rem 1.5rem;
  }

  .experiment-header {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 2rem;
  }

  .experiment-icon {
    font-size: 2.5rem;
  }

  .experiment h2 {
    font-size: 2rem;
    font-weight: 700;
    margin: 0;
    color: #fff;
  }

  .experiment-content {
    background: linear-gradient(135deg, rgba(99, 102, 241, 0.1) 0%, rgba(168, 85, 247, 0.1) 100%);
    border: 1px solid rgba(99, 102, 241, 0.2);
    border-radius: 20px;
    padding: 2.5rem;
  }

  .experiment-lead {
    font-size: 1.25rem;
    color: #e4e4e7;
    margin: 0 0 1rem;
  }

  .experiment-content > p {
    color: #a1a1aa;
    line-height: 1.7;
    margin: 0 0 1.5rem;
  }

  .experiment-content > p strong {
    color: #c4b5fd;
  }

  .experiment-stats {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 1rem;
    margin: 2rem 0;
    padding: 1.5rem;
    background: rgba(0, 0, 0, 0.3);
    border-radius: 12px;
  }

  .stat {
    text-align: center;
  }

  .stat-value {
    display: block;
    font-size: 2rem;
    font-weight: 700;
    color: #a5b4fc;
    font-family: 'JetBrains Mono', monospace;
  }

  .stat-label {
    font-size: 0.8rem;
    color: #71717a;
    margin-top: 0.25rem;
    display: block;
  }

  .experiment-note {
    font-size: 0.9rem;
    color: #71717a;
    margin: 0;
    padding-top: 1rem;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
  }

  /* Tools Section */
  .tools {
    max-width: 900px;
    margin: 0 auto;
    padding: 5rem 1.5rem;
  }

  .section-header {
    text-align: center;
    margin-bottom: 3rem;
  }

  .section-header h2 {
    font-size: 2rem;
    font-weight: 700;
    margin: 0 0 0.5rem;
    color: #fff;
  }

  .section-header p {
    color: #71717a;
    margin: 0;
  }

  .tools-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 1rem;
  }

  .tool-card {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 1.25rem 1.5rem;
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 14px;
    text-decoration: none;
    color: inherit;
    transition: all 0.2s ease;
  }

  a.tool-card:hover {
    background: rgba(99, 102, 241, 0.1);
    border-color: rgba(99, 102, 241, 0.3);
    transform: translateX(4px);
  }

  .tool-card.coming {
    opacity: 0.5;
  }

  .tool-icon {
    font-size: 2rem;
    width: 50px;
    height: 50px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(255, 255, 255, 0.05);
    border-radius: 12px;
    flex-shrink: 0;
  }

  .tool-content {
    flex: 1;
    min-width: 0;
  }

  .tool-content h3 {
    font-size: 1rem;
    font-weight: 600;
    margin: 0 0 0.25rem;
    color: #e4e4e7;
  }

  .tool-content p {
    font-size: 0.85rem;
    color: #71717a;
    margin: 0;
  }

  .tool-arrow {
    color: #6366f1;
    font-size: 1.25rem;
    opacity: 0;
    transition: opacity 0.2s, transform 0.2s;
  }

  a.tool-card:hover .tool-arrow {
    opacity: 1;
    transform: translateX(4px);
  }

  .coming-badge {
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #71717a;
    background: rgba(255, 255, 255, 0.05);
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
  }

  /* How It Works */
  .how-it-works {
    max-width: 800px;
    margin: 0 auto;
    padding: 5rem 1.5rem;
  }

  .steps {
    display: flex;
    align-items: flex-start;
    justify-content: center;
    gap: 0;
  }

  .step {
    flex: 1;
    text-align: center;
    padding: 0 1rem;
    max-width: 200px;
  }

  .step-icon {
    font-size: 2.5rem;
    margin-bottom: 1rem;
  }

  .step h3 {
    font-size: 1.1rem;
    font-weight: 600;
    margin: 0 0 0.5rem;
    color: #e4e4e7;
  }

  .step p {
    font-size: 0.9rem;
    color: #71717a;
    margin: 0;
    line-height: 1.5;
  }

  .step-connector {
    width: 60px;
    height: 2px;
    background: linear-gradient(90deg, #6366f1 0%, #a855f7 100%);
    margin-top: 2rem;
    flex-shrink: 0;
  }

  /* Request Section */
  .request {
    padding: 5rem 1.5rem;
    background: linear-gradient(180deg, transparent 0%, rgba(99, 102, 241, 0.05) 100%);
  }

  .request-content {
    max-width: 600px;
    margin: 0 auto;
    text-align: center;
  }

  .request h2 {
    font-size: 2rem;
    font-weight: 700;
    margin: 0 0 1rem;
    color: #fff;
  }

  .request p {
    color: #a1a1aa;
    margin: 0 0 2rem;
    line-height: 1.6;
  }

  .btn-request {
    display: inline-flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem 2rem;
    background: linear-gradient(135deg, #a855f7 0%, #6366f1 100%);
    color: white;
    font-size: 1rem;
    font-weight: 600;
    border-radius: 12px;
    text-decoration: none;
    transition: all 0.2s ease;
    box-shadow: 0 4px 20px rgba(168, 85, 247, 0.3);
  }

  .btn-request:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 30px rgba(168, 85, 247, 0.4);
  }

  /* Footer */
  footer {
    padding: 3rem 1.5rem;
    border-top: 1px solid rgba(255, 255, 255, 0.08);
  }

  .footer-content {
    max-width: 800px;
    margin: 0 auto;
    text-align: center;
  }

  .footer-brand {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    font-weight: 600;
    color: #e4e4e7;
    margin-bottom: 0.5rem;
  }

  .footer-logo {
    font-size: 1.25rem;
  }

  .footer-experiment {
    font-size: 0.85rem;
    color: #71717a;
    margin: 0 0 1rem;
  }

  .footer-links {
    font-size: 0.85rem;
    color: #52525b;
  }

  .footer-links a {
    color: #6366f1;
    text-decoration: none;
  }

  .footer-links a:hover {
    text-decoration: underline;
  }

  .footer-sep {
    margin: 0 0.75rem;
    color: #3f3f46;
  }

  /* Responsive */
  @media (max-width: 640px) {
    .hero {
      min-height: auto;
      padding: 3rem 1rem;
    }

    .hero h1 {
      font-size: 2rem;
    }

    .hero-subtitle {
      font-size: 1rem;
    }

    .join-inline {
      flex-direction: column;
    }

    .experiment-stats {
      grid-template-columns: 1fr;
      gap: 1.5rem;
    }

    .steps {
      flex-direction: column;
      gap: 2rem;
    }

    .step-connector {
      width: 2px;
      height: 40px;
      margin: 0 auto;
    }

    .step {
      max-width: none;
    }

    .tools-grid {
      grid-template-columns: 1fr;
    }
  }
</style>
