#!/bin/bash
# Cleanup Script - Remove Unused Legacy Code
# Based on UNUSED_FILES_REPORT.md

set -e  # Exit on error

echo "🧹 Starting cleanup of unused legacy code..."
echo ""

# Track what we're removing
REMOVED_COUNT=0

# Function to safely remove and count
safe_remove() {
    local path=$1
    if [ -e "$path" ]; then
        rm -rf "$path"
        echo "  ✅ Removed: $path"
        REMOVED_COUNT=$((REMOVED_COUNT + 1))
    else
        echo "  ⏭️  Already gone: $path"
    fi
}

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔴 HIGH PRIORITY - Unused Admin Pages"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
safe_remove "src/routes/admin/alerting"
safe_remove "src/routes/admin/audit"
safe_remove "src/routes/admin/dashboard"
safe_remove "src/routes/admin/health"
safe_remove "src/routes/admin/lifecycle"
safe_remove "src/routes/admin/monitoring"
safe_remove "src/routes/admin/organizers"
safe_remove "src/routes/admin/resilience"
# Remove parent if empty
if [ -d "src/routes/admin" ] && [ -z "$(ls -A src/routes/admin)" ]; then
    rmdir src/routes/admin
    echo "  ✅ Removed empty: src/routes/admin/"
fi
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔴 Unused Libraries"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
safe_remove "src/lib/achievements"
safe_remove "src/lib/gdpr"
safe_remove "src/lib/offline"
safe_remove "src/lib/backup"
safe_remove "src/lib/components/achievements"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔴 Unused Components (96 components)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
# Remove unused components from report
safe_remove "src/lib/components/ActionQueueViewer.svelte"
safe_remove "src/lib/components/ActivityController.svelte"
safe_remove "src/lib/components/ActivityInterface.svelte"
safe_remove "src/lib/components/ActivityTimerManager.svelte"
safe_remove "src/lib/components/AnalyticsDashboard.svelte"
safe_remove "src/lib/components/AssignmentPreview.svelte"
safe_remove "src/lib/components/AuthGuard.svelte"
safe_remove "src/lib/components/BottomNavigation.svelte"
safe_remove "src/lib/components/CloningSuccessDialog.svelte"
safe_remove "src/lib/components/ConnectionHealthMonitor.svelte"
safe_remove "src/lib/components/ConnectionStatusIndicator.svelte"
safe_remove "src/lib/components/DiscussionGroupManager.svelte"
safe_remove "src/lib/components/DiscussionInterface.svelte"
safe_remove "src/lib/components/EventCloningInterface.svelte"
safe_remove "src/lib/components/EventSelector.svelte"
safe_remove "src/lib/components/EventTemplateList.svelte"
safe_remove "src/lib/components/GameControls.svelte"
safe_remove "src/lib/components/GameInterface.svelte"
safe_remove "src/lib/components/HelpPanel.svelte"
safe_remove "src/lib/components/HelpTooltip.svelte"
safe_remove "src/lib/components/Hero.svelte"
safe_remove "src/lib/components/LateJoinerAssignment.svelte"
safe_remove "src/lib/components/MobileNavigation.svelte"
safe_remove "src/lib/components/OfflineIndicator.svelte"
safe_remove "src/lib/components/OfflineManager.svelte"
safe_remove "src/lib/components/OrganizerDashboard.svelte"
safe_remove "src/lib/components/ParticipantDashboard.svelte"
safe_remove "src/lib/components/ParticipantImporter.svelte"
safe_remove "src/lib/components/ParticipantManager.svelte"
safe_remove "src/lib/components/PermissionGuard.svelte"
safe_remove "src/lib/components/PlayerStatusList.svelte"
safe_remove "src/lib/components/QRScanner.svelte"
safe_remove "src/lib/components/ReconnectionPrompt.svelte"
safe_remove "src/lib/components/RoleGuard.svelte"
safe_remove "src/lib/components/RoomCard.svelte"
safe_remove "src/lib/components/TeamAssignmentBroadcast.svelte"
safe_remove "src/lib/components/TeamAssignmentInterface.svelte"
safe_remove "src/lib/components/TeamDistributionEditor.svelte"
safe_remove "src/lib/components/TeamDistributionPreview.svelte"
safe_remove "src/lib/components/TemplateCreationForm.svelte"
safe_remove "src/lib/components/TemplateCreationWizard.svelte"
safe_remove "src/lib/components/TemplateDiscoveryInterface.svelte"
safe_remove "src/lib/components/TemplatePermissionGuard.svelte"
safe_remove "src/lib/components/TemplatePreview.svelte"
safe_remove "src/lib/components/TemplatePreviewModal.svelte"
safe_remove "src/lib/components/TemplateSharingHistory.svelte"
safe_remove "src/lib/components/TemplateSharingInterface.svelte"
safe_remove "src/lib/components/TopicList.svelte"
safe_remove "src/lib/components/TopicListWithVoting.svelte"
safe_remove "src/lib/components/TopicSubmissionForm.svelte"
safe_remove "src/lib/components/ValidatedEventJoin.svelte"
safe_remove "src/lib/components/VotingInterface.svelte"
safe_remove "src/lib/components/WebSocketTest.svelte"
safe_remove "src/lib/components/WeightedVoting.svelte"
safe_remove "src/lib/components/WordChainGame.svelte"
safe_remove "src/lib/components/WordChainModeSelector.svelte"
safe_remove "src/lib/components/WordChainTimeline.svelte"
safe_remove "src/lib/components/WordSubmissionInput.svelte"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟠 Legacy Game System"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
safe_remove "src/lib/games/word-chain"
safe_remove "src/test/games"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟠 Unused Utilities"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
safe_remove "src/lib/utils/cache.ts"
safe_remove "src/lib/utils/csv-parser.ts"
safe_remove "src/lib/utils/late-joiner-handler.ts"
safe_remove "src/lib/utils/lazy-loading.ts"
safe_remove "src/lib/utils/mobile-performance.ts"
safe_remove "src/lib/utils/team-assignment-broadcast.ts"
safe_remove "src/lib/utils/team-distribution.ts"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟠 Unused Stores"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
safe_remove "src/lib/stores/discussionGroupStore.ts"
safe_remove "src/lib/stores/topicStore.ts"
safe_remove "src/lib/stores/votingStore.ts"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟠 Empty Route Folders"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
safe_remove "src/routes/achievements"
safe_remove "src/routes/voting-demo"
safe_remove "src/routes/api/achievements"
safe_remove "src/routes/api/gdpr"
safe_remove "src/routes/api/backup"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟠 Unused API Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
safe_remove "src/routes/api/discussion-groups"
safe_remove "src/routes/api/templates"
safe_remove "src/routes/api/alerting"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Cleanup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Summary:"
echo "  • Removed $REMOVED_COUNT items"
echo ""
echo "🔍 Next steps:"
echo "  1. Run: npm run check       # Verify TypeScript errors reduced"
echo "  2. Run: npm run build       # Ensure build still works"
echo "  3. Run: npm run test:unit   # Ensure tests pass"
echo "  4. Review changes: git status"
echo "  5. Commit: git add -A && git commit -m 'chore: remove unused legacy code'"
echo ""
